const categoryDatas = [
  {
    category: "Grocery",
    emoji: "🛒",
    image: "https://via.placeholder.com/120?text=Grocery",
    items: [
      "Dals",
      "Pulses",
      "Dry Fruits",
      "Cooking Oil",
      "Ghee & Vanaspati",
      "Flours & Grains",
      "Rice & Rice Products",
      "Masala & Spices",
      "Salt / Sugar / Jaggery",
    ],
  },
  {
    category: "Personal Care & Beauty",
    emoji: "💄",
    image: "https://via.placeholder.com/120?text=Beauty",
    items: [
      "Skin Care",
      "Makeup",
      "Face & Body",
      "Hair Care",
      "Oral Care",
      "Personal Hygiene",
      "Men’s Grooming",
      "Fragrances",
      "Health & Wellness",
      "Appliances",
    ],
  },
  {
    category: "Footwear",
    emoji: "👟",
    image: "https://via.placeholder.com/120?text=Footwear",
    items: [
      "Men’s Footwear",
      "Women’s Footwear",
      "Kid’s Footwear",
      "Shoe Care",
    ],
  },
  {
    category: "Gifting",
    emoji: "🎁",
    image: "https://via.placeholder.com/120?text=Gifting",
    items: [
      "Bulk Gifting",
      "Chocolate Gift Packs",
      "General Gifts",
      "Gift Bags & Wrapping Paper",
      "Kids Gifts",
      "Appliances",
    ],
  },
  {
    category: "Daily & Beverages",
    emoji: "🥛",
    image: "https://via.placeholder.com/120?text=Daily",
    items: ["Dairy", "Beverages", "Juices", "Tea & Coffee"],
  },
  {
    category: "Kitchen & Dining",
    emoji: "🍽️",
    image: "https://via.placeholder.com/120?text=Kitchen",
    items: [
      "Storage & Organizers",
      "Cookware",
      "Kitchen Tools",
      "Cutlery",
      "Glassware",
      "Dinnerware",
      "Appliances",
    ],
  },
  {
    category: "Books",
    emoji: "📚",
    image: "https://via.placeholder.com/120?text=Books",
    items: [
      "Fiction",
      "Non-Fiction",
      "Children’s Books",
      "Educational",
      "Cookbooks",
      "Religious",
      "Comics",
    ],
  },
  {
    category: "Clothing & Accessories",
    emoji: "👕",
    image: "https://via.placeholder.com/120?text=Clothing",
    items: ["Men’s Wear", "Women’s Wear", "Accessories"],
  },
  {
    category: "Seasonal & More",
    emoji: "🎉",
    image: "https://via.placeholder.com/120?text=Seasonal",
    items: ["Festive Specials", "Decorations", "Seasonal Needs"],
  },
  {
    category: "Packaged Food",
    emoji: "🍪",
    image: "https://via.placeholder.com/120?text=Food",
    items: [
      "Biscuits & Cookies",
      "Snacks & Namkeen",
      "Breakfast Cereals",
      "Noodles & Pasta",
      "Ready to Cook",
      "Sweets",
      "Pickles",
      "Health Food",
      "Frozen Foods",
    ],
  },
  {
    category: "Sports & Fitness",
    emoji: "🏅",
    image: "https://via.placeholder.com/120?text=Sports",
    items: ["Outdoor Sports", "Indoor Sports", "Fitness"],
  },
  {
    category: "Electronics & Appliances",
    emoji: "🔌",
    image: "https://via.placeholder.com/120?text=Electronics",
    items: [
      "Electrical Items",
      "Kitchen Appliances",
      "Home Appliances",
      "Computer Accessories",
      "Mobile Accessories",
    ],
  },
  {
    category: "Shop by Room",
    emoji: "🏠",
    image: "https://via.placeholder.com/120?text=Home",
    items: [
      "Living Room",
      "Bedroom",
      "Kitchen",
      "Dining Room",
      "Bathroom",
      "Outdoor",
    ],
  },
  {
    category: "Fruits & Vegetables",
    emoji: "🍎",
    image: "https://via.placeholder.com/120?text=Fruits",
    items: [
      "Fresh Fruits",
      "Vegetables",
      "Exotic Fruits",
      "Leafy Vegetables",
      "Sprouts",
    ],
  },
  {
    category: "Home Furnishing & Decor",
    emoji: "🛏️",
    image: "https://via.placeholder.com/120?text=Decor",
    items: [
      "Bedsheets",
      "Curtains",
      "Mats & Carpets",
      "Home Decor",
      "Table Covers",
      "Furniture",
    ],
  },
  {
    category: "Baby Care",
    emoji: "🍼",
    image: "https://via.placeholder.com/120?text=Baby",
    items: ["Diapers", "Baby Skin Care", "Baby Food", "Baby Gear", "Kids Toys"],
  },
  {
    category: "Bags & More",
    emoji: "🧳",
    image: "https://via.placeholder.com/120?text=Bags",
    items: ["Backpacks", "Handbags", "Travel Bags", "Wallets"],
  },
  {
    category: "Home & Kitchen Essentials",
    emoji: "🧼",
    image: "https://via.placeholder.com/120?text=Home+Care",
    items: [
      "Cleaners",
      "Detergents",
      "Toilet Cleaners",
      "Dishwashers",
      "Sanitizers",
      "Tissues & Napkins",
      "Pocha Needs",
    ],
  },
  {
    category: "Stationery",
    emoji: "✏️",
    image: "https://via.placeholder.com/120?text=Stationery",
    items: [
      "Pens & Notebooks",
      "Art & Craft",
      "General Stationery",
      "Gift Wraps",
    ],
  },
  {
    category: "Home Utility & Organisers",
    emoji: "🧹",
    image: "https://via.placeholder.com/120?text=Utility",
    items: [
      "Cleaning Tools",
      "Laundry Essentials",
      "Racks & Organizers",
      "Storage Boxes",
      "Plastic Ware",
      "Bathroom Needs",
    ],
  },
];

export default categoryDatas;
